"""empty message

Revision ID: 04672d9a2578
Revises: ec10a5246896
Create Date: 2017-10-29 11:16:04.717825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04672d9a2578'
down_revision = 'ec10a5246896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remoteusers', sa.Column('is_amadmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remoteusers', 'is_amadmin')
    # ### end Alembic commands ###
