"""empty message

Revision ID: 125bcb0726f3
Revises: 04672d9a2578
Create Date: 2017-10-29 12:08:42.688216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125bcb0726f3'
down_revision = '04672d9a2578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remoteusers', sa.Column('is_pmadmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remoteusers', 'is_pmadmin')
    # ### end Alembic commands ###
