"""empty message

Revision ID: 20964ae25423
Revises: 7aefd98a48d5
Create Date: 2017-10-28 22:27:55.293828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20964ae25423'
down_revision = '7aefd98a48d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staffrequests', sa.Column('hrcomment', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staffrequests', 'hrcomment')
    # ### end Alembic commands ###
