"""empty message

Revision ID: 23e7bb60ece8
Revises: 57a3b046207b
Create Date: 2017-10-19 13:25:57.970606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e7bb60ece8'
down_revision = '57a3b046207b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('task', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'task')
    # ### end Alembic commands ###
