"""empty message

Revision ID: 34f2be3aa18e
Revises: b5b91f0ad4d7
Create Date: 2017-10-23 11:33:19.685051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34f2be3aa18e'
down_revision = 'b5b91f0ad4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('listeventid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_listeventid'), 'tasks', ['listeventid'], unique=True)
    op.drop_index('ix_tasks_eventid', table_name='tasks')
    op.drop_column('tasks', 'eventid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('eventid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('ix_tasks_eventid', 'tasks', ['eventid'], unique=True)
    op.drop_index(op.f('ix_tasks_listeventid'), table_name='tasks')
    op.drop_column('tasks', 'listeventid')
    # ### end Alembic commands ###
