"""empty message

Revision ID: 4d0b083c94d1
Revises: e53235e6a37d
Create Date: 2017-11-02 10:47:15.632095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0b083c94d1'
down_revision = 'e53235e6a37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_listeventid', table_name='tasks')
    op.create_index(op.f('ix_tasks_listeventid'), 'tasks', ['listeventid'], unique=False)
    op.drop_index('taskname', table_name='tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('taskname', 'tasks', ['taskname'], unique=True)
    op.drop_index(op.f('ix_tasks_listeventid'), table_name='tasks')
    op.create_index('ix_tasks_listeventid', 'tasks', ['listeventid'], unique=True)
    # ### end Alembic commands ###
