"""empty message

Revision ID: 5f971dbc1900
Revises: db687ad98f56
Create Date: 2017-10-15 13:42:32.631964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f971dbc1900'
down_revision = 'db687ad98f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('appstatus', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'appstatus')
    # ### end Alembic commands ###
