"""empty message

Revision ID: 7aefd98a48d5
Revises: f7e70dfb284e
Create Date: 2017-10-28 01:12:18.432706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aefd98a48d5'
down_revision = 'f7e70dfb284e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remoteusers', sa.Column('is_hradmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remoteusers', 'is_hradmin')
    # ### end Alembic commands ###
