"""empty message

Revision ID: 8cac5a6730fc
Revises: 0056e11132bf
Create Date: 2017-10-23 02:58:23.493748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cac5a6730fc'
down_revision = '0056e11132bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(u'tasks_ibfk_1', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'event_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'tasks_ibfk_1', 'tasks', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'task_id')
    # ### end Alembic commands ###
