"""empty message

Revision ID: a3178a7d6d0d
Revises: 5f971dbc1900
Create Date: 2017-10-16 18:04:04.245455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3178a7d6d0d'
down_revision = '5f971dbc1900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('emailrecepient', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('emailsent', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'emailsent')
    op.drop_column('events', 'emailrecepient')
    # ### end Alembic commands ###
