"""empty message

Revision ID: abd3fa4c6d00
Revises: 125bcb0726f3
Create Date: 2017-10-29 17:20:50.462369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd3fa4c6d00'
down_revision = '125bcb0726f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remoteusers', sa.Column('is_music_sbtadmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remoteusers', 'is_music_sbtadmin')
    # ### end Alembic commands ###
