"""empty message

Revision ID: b5b91f0ad4d7
Revises: 8f098cbe52c5
Create Date: 2017-10-23 11:30:17.954218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b91f0ad4d7'
down_revision = '8f098cbe52c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('eventid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_eventid'), 'tasks', ['eventid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_eventid'), table_name='tasks')
    op.drop_column('tasks', 'eventid')
    # ### end Alembic commands ###
