"""empty message

Revision ID: b6c078fac8df
Revises: 23e7bb60ece8
Create Date: 2017-10-19 14:49:08.758224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c078fac8df'
down_revision = '23e7bb60ece8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'task_id')
    # ### end Alembic commands ###
