"""empty message

Revision ID: e53235e6a37d
Revises: abd3fa4c6d00
Create Date: 2017-10-29 17:56:14.605683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53235e6a37d'
down_revision = 'abd3fa4c6d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('sbtcomments', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'sbtcomments')
    # ### end Alembic commands ###
