"""empty message

Revision ID: f7e70dfb284e
Revises: 34f2be3aa18e
Create Date: 2017-10-28 00:10:35.249220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e70dfb284e'
down_revision = '34f2be3aa18e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staffrequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requestname', sa.String(length=50), nullable=True),
    sa.Column('contracttype', sa.String(length=50), nullable=True),
    sa.Column('departmentname', sa.String(length=50), nullable=True),
    sa.Column('jobtitle', sa.String(length=50), nullable=True),
    sa.Column('jobdescription', sa.String(length=200), nullable=True),
    sa.Column('requeststatus', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staffrequests')
    # ### end Alembic commands ###
